// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserLogin.Data;

#nullable disable

namespace UserLogin.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UserLogin.Models.CartItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("HeadphoneId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("HeadphoneId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("UserLogin.Models.Headphones", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Headphones");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Category = "ladies",
                            Description = "Dive into immersive audio with rich bass and sharp highs for the perfect listening experience.",
                            Image = "Headphone-1.webp",
                            Price = 59,
                            Title = "BassPro X1 Wireless Headphones"
                        },
                        new
                        {
                            Id = "2",
                            Category = "ladies",
                            Description = "Lightweight design with cushioned ear cups for extended wear without fatigue.",
                            Image = "Headphone-2.webp",
                            Price = 39,
                            Title = "AeroSound Lite"
                        },
                        new
                        {
                            Id = "3",
                            Category = "ladies",
                            Description = "Block out the world and focus on what matters with advanced noise cancellation.",
                            Image = "Headphone-3.webp",
                            Price = 79,
                            Title = "SilenceCore 700"
                        },
                        new
                        {
                            Id = "4",
                            Category = "ladies",
                            Description = "Enjoy tangle-free listening with seamless Bluetooth connectivity.",
                            Image = "Headphone-4.webp",
                            Price = 49,
                            Title = "WaveConnect Pro"
                        },
                        new
                        {
                            Id = "5",
                            Category = "ladies",
                            Description = "Feel every beat with powerful low-end response that brings music to life.",
                            Image = "Headphone-5.webp",
                            Price = 65,
                            Title = "ThunderBeat Max"
                        },
                        new
                        {
                            Id = "6",
                            Category = "ladies",
                            Description = "Compact, foldable design makes these headphones travel-ready and space-saving.",
                            Image = "Headphone-6.png",
                            Price = 42,
                            Title = "FoldX Compact"
                        },
                        new
                        {
                            Id = "7",
                            Category = "ladies",
                            Description = "Stay unplugged longer with up to 24 hours of continuous playback.",
                            Image = "Headphone-7.webp",
                            Price = 55,
                            Title = "EchoPlay 24H"
                        },
                        new
                        {
                            Id = "8",
                            Category = "ladies",
                            Description = "Easy tap-and-swipe gestures let you control playback and calls with ease.",
                            Image = "Headphone-8.webp",
                            Price = 53,
                            Title = "TouchTune Air"
                        },
                        new
                        {
                            Id = "9",
                            Category = "ladies",
                            Description = "Built-in mic with noise reduction for flawless voice clarity on the go.",
                            Image = "Headphone-9.webp",
                            Price = 44,
                            Title = "CallClear Vibe"
                        },
                        new
                        {
                            Id = "10",
                            Category = "ladies",
                            Description = "Perfect for workouts and runs with water-resistant durability.",
                            Image = "Headphone-10.webp",
                            Price = 47,
                            Title = "RunSound Active"
                        },
                        new
                        {
                            Id = "11",
                            Category = "ladies",
                            Description = "Hear music the way it was meant to be with high-fidelity sound tuning.",
                            Image = "Headphone-11.webp",
                            Price = 69,
                            Title = "HiFi Aura 360"
                        });
                });

            modelBuilder.Entity("UserLogin.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserLogin.Models.CartItems", b =>
                {
                    b.HasOne("UserLogin.Models.Headphones", "Headphone")
                        .WithMany("CartItems")
                        .HasForeignKey("HeadphoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserLogin.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Headphone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserLogin.Models.Headphones", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("UserLogin.Models.User", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
